 	
#!/bin/bash
source config
cp local.conf devstack
DEPLOYMENT_CONFIG_FILE=/home/stack/devstack/local.conf

#Update config file
sed -i 's/HOST_IP=/HOST_IP='$MNT_IP'/g' $DEPLOYMENT_CONFIG_FILE
sed -i 's/HOST_IP_IFACE=/HOST_IP_IFACE='$MNT_IF'/g' $DEPLOYMENT_CONFIG_FILE
sed -i 's/PUBLIC_INTERFACE=/PUBLIC_INTERFACE='$PUBLIC_INTERFACE'/g' $DEPLOYMENT_CONFIG_FILE
sed -i 's/VLAN_INTERFACE=/VLAN_INTERFACE='$TENAT_IF'/g' $DEPLOYMENT_CONFIG_FILE
sed -i 's/FLAT_INTERFACE=/FLAT_INTERFACE='$TENAT_IF'/g' $DEPLOYMENT_CONFIG_FILE
sed -i 's/OVS_PHYSICAL_BRIDGE=/OVS_PHYSICAL_BRIDGE=br-'$TENAT_IF'/g' $DEPLOYMENT_CONFIG_FILE

